 services:
# ---------------------------- container for app - start on port 5050
  # odrprocesing:
  #   build:
  #     context: .
  #     dockerfile: cmd/processing/Dockerfile
  #   container_name: ODRProcesing-env
  #   environment:
  #     HTTP_ADDR: ":5050"
  #     HTTP_SHUTDOWN_TIMEOUT: ${HTTP_SHUTDOWN_TIMEOUT}
  #     POSTGRES_HOST: ODRProcesing-postgres
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_TIMEOUT: ${POSTGRES_TIMEOUT}
  #     LOGGER_LEVEL: ${LOGGER_LEVEL}
  #     TIME_ZONE: ${TIME_ZONE}
  #     LOGGER_FOLDER: ${LOGGER_FOLDER}
  #   ports:
  #     - "5050:5050"
  #   restart: always


#  container for DB
  ODRProcesing-postgres:
    image: postgres:16
    container_name: ODRProcesing-env-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # - ${PROJECT_ROOT}/pgdata:/var/lib/postgresql/data
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - "5433:5432" 
    restart: always

  ODRProcesing-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
    - ./migrations:/migrations
    # - ${PROJECT_ROOT}/migrations:/migrations

  swagger:
    build:
  #   context: ${PROJECT_ROOT}
      context: .
      dockerfile_inline: |
        FROM golang:1.26.1-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
#      - ${PROJECT_ROOT}:/code
      - ./:/code

  # ODRProcesing-port-forwarder:
  #  image: alpine/socat:1.8.0.3
  #  container_name: ODRProcesing-port-forwarder
  #  command:
  #   - socat
  #   - TCP-LISTEN:5432,fork
  #   - TCP:ODRProcesing-postgres:5432
  #  ports:
  #   - "127.0.0.1:5433:5432"


