FROM golang:1.26.1-bookworm AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/exe ./services/reservation/cmd/reservation

FROM alpine:3.23
WORKDIR /app
COPY --from=builder /app/exe .
ENV PROJECT_ROOT=/app
EXPOSE 8091
CMD ["./exe"]
